import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

import Header from "@/components/header/Header";

const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sports Scoreboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        <Header />
        <div className="container mx-auto py-6 px-2">
          {children}
        </div>
      </body>
    </html>
  );
}
